### ISSUE TITLE
Library doesn't appear in lib manager

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_SHTC3_Arduino_Library#1]
Did this lib ever get posted to Arduino for inclusion?

![image](https://user-images.githubusercontent.com/117102/60857216-f1923c00-a1c6-11e9-9528-2ff42bb9a593.png)

**Comment by oclyke** [comment]
[Oops](https://github.com/arduino/Arduino/issues/8139)

Fixing now.

**Comment by oclyke** [comment]
Should be resolved. Arduino should pick it up within an hour. Waiting for confirmation before closing issue.

**Comment by bboyho** [comment]
The Arduino Library Manager can find it now. I am closing this out. ;)
