### ISSUE TITLE
No need to clear the buffer of the Wire library.

### ISSUE THREAD

**Issue by Koepel** [sparkfun/SparkFun_SHTC3_Arduino_Library#2]
In the file "src/SparkFun_SHTC3.cpp" is in two places this code to clear the buffer before calling a Wire.requestFrom():
```
while (_wire->available())
{
  _wire->read();
}
```
It is not needed to clear the buffer. When the Wire.requesFrom() is called it clears the buffers and variables before starting the I2C session.
Explanation: [Common-mistakes#4](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#4)

This is not even a bug, but that code is not needed.

**Comment by oclyke** [comment]
Thanks @Koepel - your document about common mistakes with Wire is also very interesting to refer to. 

I've created a PR (#3) with what I think are the changes you suggest. I will leave the PR open until either someone else or I has the opportunity to test the changes and make a release.

**Comment by nseidle** [comment]
Merged and released in v1.1.3.
