### ISSUE TITLE
LICENSE.md missing

### ISSUE THREAD

**Issue by stepheneb** [sparkfun/SparkFun_SHTC3_Arduino_Library#4]
`README.md` describes this library as licensed under the GPL3 and refers to `LICENSE.md`.  The file  `LICENSE.md` doesn't appear to be in the repository.

**Comment by bboyho** [comment]
Hi! 

Nice catch! I just noticed your issue when updating the README.md. Hmm, I think the engineer that originally wrote it didn't include it into this library. I just added the LICENSE.md that we usually use for our hardware and the one he intended to link for the code.
